SET SERVEROUTPUT ON;

DROP VIEW PRODUC1;
DROP VIEW CAT;
DROP VIEW PROD;
DROP VIEW FAC1;


CREATE VIEW PRODUC1 AS(
SELECT P.NOMBRE, P.ID_PRODUCTOS, U.NOMBREU, U.CORREO, U.ID_CLIENTE
FROM USUARIO U INNER JOIN CARRITO C 
ON U.ID_CARRITO = C.ID_CARRITO INNER JOIN PRODUCTOS P
ON C.ID_PRODUCTOS = P.ID_PRODUCTOS
);

SELECT * FROM PRODUC;

SELECT NOMBRE, NOMBREU, CORREO, ID_CLIENTE
FROM PRODUC1
WHERE ID_CLIENTE = '&ID_CLIENTE';


DECLARE
    V_ID PRODUC1.ID_CLIENTE%TYPE := '&ID_CLIENTE';
    V_TODO PRODUC1%ROWTYPE;
BEGIN
    SELECT *
    INTO V_TODO
    FROM PRODUC1
    WHERE ID_CLIENTE = V_ID;
    DBMS_OUTPUT.PUT_LINE('USUARIO: ' || V_TODO.NOMBREU); 
	DBMS_OUTPUT.PUT_LINE('CORREO: ' || V_TODO.CORREO); 
	DBMS_OUTPUT.PUT_LINE('PRODUCTO: ' || V_TODO.NOMBRE); 
END;

------------------------------------------------------------------------
DECLARE
    V_ID USUARIO.ID_CLIENTE%TYPE := '&ID_CLIENTE';
    V_TODO USUARIO%ROWTYPE;
BEGIN
    SELECT *
    INTO V_TODO
    FROM USUARIO
    WHERE ID_CLIENTE = V_ID;
    DBMS_OUTPUT.PUT_LINE('EL ID ES: ' || V_TODO.ID_CLIENTE);
    DBMS_OUTPUT.PUT_LINE('USUARIO: ' || V_TODO.NOMBREU); 
	DBMS_OUTPUT.PUT_LINE('CORREO: ' || V_TODO.CORREO); 
	DBMS_OUTPUT.PUT_LINE('TELEFONO: ' || V_TODO.TELEFONO); 
END;

------------------------------------------------------------------------

CREATE VIEW CAT AS(
SELECT P.ID_PRODUCTOS, P.NOMBRE, P.PRECIO, C.CATALOGO
FROM PRODUCTOS P INNER JOIN CATEGORIA C
ON P.ID_CATEGORIA = C.ID_CATEGORIA
);

SELECT * FROM CAT;

DECLARE
    V_ID PRODUCTOS.ID_PRODUCTOS%TYPE := '&ID_PRODUCTO';
    V_TODO CAT%ROWTYPE;
BEGIN
    SELECT *
    INTO V_TODO
    FROM CAT
    WHERE ID_PRODUCTOS = V_ID;
    DBMS_OUTPUT.PUT_LINE('EL ID ES: ' || V_TODO.ID_PRODUCTOS);
    DBMS_OUTPUT.PUT_LINE('NOMBRE: ' || V_TODO.NOMBRE); 
	DBMS_OUTPUT.PUT_LINE('PRECIO: ' || V_TODO.PRECIO); 
	DBMS_OUTPUT.PUT_LINE('DE LA CATEGORIA: ' || V_TODO.CATALOGO); 
END;

------------------------------------------------------------------------

CREATE VIEW PROD AS(
SELECT P.ID_PRODUCTOS, P.NOMBRE, P.GARANTIA, P.PRECIO, I.EXISTENCIAS, C.CATALOGO 
FROM CATEGORIA C INNER JOIN PRODUCTOS P
ON C.ID_CATEGORIA = P.ID_CATEGORIA INNER JOIN INVENTARIO I
ON P.ID_INVENTARIO = I.ID_INVENTARIO
);

SELECT * FROM PROD;

DECLARE
    V_ID PRODUCTOS.ID_PRODUCTOS%TYPE := '&ID_PRODUCTOS';
    V_TODO PROD%ROWTYPE;
BEGIN
    SELECT *
    INTO V_TODO
    FROM PROD
    WHERE ID_PRODUCTOS = V_ID;
    DBMS_OUTPUT.PUT_LINE('EL ID ES: ' || V_TODO.ID_PRODUCTOS);
    DBMS_OUTPUT.PUT_LINE('PRODUCTO: ' || V_TODO.NOMBRE); 
	DBMS_OUTPUT.PUT_LINE('CATEGORIA: ' || V_TODO.CATALOGO); 
	DBMS_OUTPUT.PUT_LINE('GARANTIA: ' || V_TODO.GARANTIA);
	DBMS_OUTPUT.PUT_LINE('PRECIO: ' || V_TODO.PRECIO);
	DBMS_OUTPUT.PUT_LINE('EXISTENCIAS: ' || V_TODO.EXISTENCIAS);
END;

------------------------------------------------------------------------

CREATE VIEW FAC1 AS(
SELECT T.DESCRIPCION, T.COSTO, U.ID_CLIENTE, F.RFC, F.FACTURAR_A
FROM TIPO T INNER JOIN USUARIO U 
ON T.ID_TIPO = U.ID_TIPO INNER JOIN CARRITO C
ON U.ID_CARRITO = C.ID_CARRITO INNER JOIN TICKET TI
ON C.ID_TICKET = TI.ID_TICKET INNER JOIN FACTURA F 
ON TI.ID_FACTURA = F.ID_FACTURA
);

SELECT * FROM FAC1;

DECLARE
    V_ID USUARIO.ID_CLIENTE%TYPE := '&ID_CLIENTE';
    V_TODO FAC1%ROWTYPE;
BEGIN
    SELECT *
    INTO V_TODO
    FROM FAC1
    WHERE ID_CLIENTE = V_ID;
    DBMS_OUTPUT.PUT_LINE('EL ID ES: ' || V_TODO.ID_CLIENTE);
    DBMS_OUTPUT.PUT_LINE('MEMBRESIA: ' || V_TODO.DESCRIPCION); 
	DBMS_OUTPUT.PUT_LINE('PRECIO: ' || V_TODO.COSTO);
	DBMS_OUTPUT.PUT_LINE('RFC: ' || V_TODO.RFC);
	DBMS_OUTPUT.PUT_LINE('FACTURAR A: ' || V_TODO.FACTURAR_A);
END;




