--FUNCIONES INTEGRADAS:

SELECT NUM_RASTREO,
CASE 
	WHEN ESTATUS = 'ENVIADO' THEN 'EN EL SISTEMA'
	ELSE 'FUERA DEL SISTEMA'
END
FROM ENVIOS;

------------------------------------------------------------------------

SELECT U.NOMBREU, (SUBSTR(U.NOMBREU,3,5)) || (E.NUM_RASTREO)
FROM USUARIO U INNER JOIN CARRITO C 
ON U.ID_CARRITO = C.ID_CARRITO INNER JOIN TICKET T 
ON C.ID_TICKET =  T.ID_TICKET INNER JOIN ENVIOS E
ON T.ID_ENVIOS = E.ID_ENVIOS;

------------------------------------------------------------------------

SELECT P.NOMBRE PRODUCTO, SUM(T.MONTO) SUMATORIA , T.FECHA, C.CATALOGO CATEGORIA
FROM CATEGORIA C INNER JOIN PRODUCTOS P 
ON C.ID_CATEGORIA = P.ID_CATEGORIA INNER JOIN CARRITO C
ON P.ID_PRODUCTOS = C.ID_PRODUCTOS INNER JOIN TICKET T
ON C.ID_TICKET = T.ID_TICKET
GROUP BY P.NOMBRE,  T.FECHA, C.CATALOGO;

------------------------------------------------------------------------
--FUNCIONES CREADAS:

CREATE OR REPLACE FUNCTION MONTO_TOTAL_DESCUENTO20(P_ID_TICKET NUMBER)
RETURN NUMBER
AS
V_MONTO_TOTAL NUMBER(20);
V_MONTO_TOTAL_PAGAR NUMBER(20);
BEGIN
SELECT MONTO
INTO V_MONTO_TOTAL
FROM TICKET
WHERE ID_TICKET = P_ID_TICKET;
IF V_MONTO_TOTAL >= 1700
THEN V_MONTO_TOTAL_PAGAR := V_MONTO_TOTAL*.80; 
ELSE V_MONTO_TOTAL_PAGAR := V_MONTO_TOTAL*1;
END IF;
RETURN V_MONTO_TOTAL_PAGAR;
END;

SELECT MONTO, MONTO_TOTAL_DESCUENTO20(ID_TICKET) AS "MONTO A PAGAR"
FROM TICKET;

------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION IVA_TM2(P_ID_TIPO NUMBER)
RETURN NUMBER
AS
V_IVA_TM NUMBER(20);
V_IVA_TM_PAGAR NUMBER(20);
BEGIN
SELECT COSTO
INTO V_IVA_TM
FROM TIPO
WHERE ID_TIPO = P_ID_TIPO;
IF V_IVA_TM >= 899
THEN V_IVA_TM_PAGAR := V_IVA_TM*1.16; 
ELSE V_IVA_TM_PAGAR := V_IVA_TM*1.15;
END IF;
RETURN V_IVA_TM_PAGAR;
END;

SELECT COSTO, IVA_TM2(ID_TIPO) AS "IVA DE LA MEMBRESIA"
FROM TIPO;

COMMIT;