DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE TIPO CASCADE CONSTRAINTS;
DROP TABLE WISH_LIST CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE ENVIOS CASCADE CONSTRAINTS;
DROP TABLE FACTURA CASCADE CONSTRAINTS;
DROP TABLE TICKET CASCADE CONSTRAINTS;
DROP TABLE CARRITO CASCADE CONSTRAINTS;
DROP TABLE SERVICIOS CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_ID_PRO;
DROP SEQUENCE SQ_ID_FAC;
DROP SEQUENCE SQ_ID_TIC;
DROP SEQUENCE SQ_ID_FAC1;
DROP SEQUENCE SQ_ID_ENV;
DROP SEQUENCE SQ_ID_TIC1;
DROP SEQUENCE SQ_ID_ENV1;
DROP SEQUENCE SQ_ID_CAR;
DROP SEQUENCE SQ_ID_TIC2;
DROP SEQUENCE SQ_ID_SER;
DROP SEQUENCE SQ_U_CLI;
DROP SEQUENCE SQ_U_CAR;
DROP SEQUENCE SQ_U_TIP;
DROP SEQUENCE SQ_U_VEN;
DROP SEQUENCE SQ_U_WISH;
DROP SEQUENCE SQ_U_SER;

CREATE TABLE USUARIO(
ID_CLIENTE NUMBER(5),
NOMBREU VARCHAR(50),
EDAD NUMBER(2),
GENERO CHAR(10),
TELEFONO NUMBER(10),
CORREO VARCHAR(40),
ID_CARRITO NUMBER(5),
ID_TIPO NUMBER(10),
ID_VENDEDOR NUMBER(5),
ID_WISH NUMBER(10),
ID_SERVICIO VARCHAR (10)
);

CREATE TABLE SERVICIOS(
ID_SERVICIO VARCHAR (10),
DESCRIPCION VARCHAR(30),
COSTO NUMBER(5)
);

CREATE TABLE TIPO(
ID_TIPO NUMBER(10),
TIPO VARCHAR(7),
COSTO VARCHAR(4),
DESCRIPCION VARCHAR(14),
ID_MEMBRESIA VARCHAR(7)
);

CREATE TABLE WISH_LIST(
ID_WISH NUMBER(10),
DESCRIPCION VARCHAR(7)
);

CREATE TABLE CATEGORIA(
ID_CATEGORIA NUMBER(5),
CATALOGO VARCHAR(35)
);

CREATE TABLE INVENTARIO(
ID_INVENTARIO NUMBER(5),
EXISTENCIAS NUMBER(10)
);

CREATE TABLE PRODUCTOS(
ID_PRODUCTOS NUMBER(5),
NOMBRE VARCHAR(25),
PRECIO NUMBER(10),
GARANTIA VARCHAR(25),
ID_CATEGORIA NUMBER(5),
ID_INVENTARIO NUMBER(5)
);

CREATE TABLE ENVIOS(
ID_ENVIOS NUMBER(10),
DIRECCION VARCHAR(50),
ESTATUS VARCHAR(15),
NUM_RASTREO VARCHAR(30)
);

CREATE TABLE FACTURA(
ID_FACTURA NUMBER(10),
NOMBRE VARCHAR(50),
RFC VARCHAR(20),
DESCRIPCION VARCHAR(40),
FACTURAR_A VARCHAR(50)
);

CREATE TABLE TICKET(
ID_TICKET NUMBER(10),
ID_FACTURA NUMBER(10),
ID_ENVIOS NUMBER(10),
MONTO NUMBER(10),
FECHA DATE,
DESCRIPCION VARCHAR(20),
TIPO_ENVIO VARCHAR(20)
);

CREATE TABLE CARRITO(
ID_CARRITO NUMBER(10),
ID_TICKET NUMBER(10),
ID_PRODUCTOS NUMBER(10)
);

--PRIMARY KEY
ALTER TABLE USUARIO ADD CONSTRAINTS PK_ID_CLI PRIMARY KEY (ID_CLIENTE);
ALTER TABLE TIPO ADD CONSTRAINTS PK_ID_TIP PRIMARY KEY (ID_TIPO);
ALTER TABLE WISH_LIST ADD CONSTRAINTS PK_ID_WISH PRIMARY KEY (ID_WISH);
ALTER TABLE CATEGORIA ADD CONSTRAINTS PK_ID_CAT PRIMARY KEY (ID_CATEGORIA);
ALTER TABLE INVENTARIO ADD CONSTRAINTS PK_ID_INV PRIMARY KEY (ID_INVENTARIO);
ALTER TABLE PRODUCTOS ADD CONSTRAINTS PK_ID_PRO PRIMARY KEY (ID_PRODUCTOS);
ALTER TABLE TICKET ADD CONSTRAINTS PK_ID_TIC PRIMARY KEY (ID_TICKET);
ALTER TABLE FACTURA ADD CONSTRAINTS PK_ID_FAC PRIMARY KEY (ID_FACTURA);
ALTER TABLE CARRITO ADD CONSTRAINTS PK_ID_CAR PRIMARY KEY (ID_CARRITO);
ALTER TABLE ENVIOS ADD CONSTRAINTS PK_ID_ENV PRIMARY KEY (ID_ENVIOS);
ALTER TABLE SERVICIOS ADD CONSTRAINTS PK_ID_SER PRIMARY KEY (ID_SERVICIO);

--FOREIGN KEY
ALTER TABLE PRODUCTOS ADD CONSTRAINTS FK_PRO_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA);
ALTER TABLE PRODUCTOS ADD CONSTRAINTS FK_PRO_INV FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO (ID_INVENTARIO);

ALTER TABLE TICKET ADD CONSTRAINTS FK_TIC_FAC FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA (ID_FACTURA);

ALTER TABLE USUARIO ADD CONSTRAINTS FK_USU_TIP FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID_TIPO);
ALTER TABLE USUARIO ADD CONSTRAINTS FK_USU_WIS FOREIGN KEY (ID_WISH) REFERENCES WISH_LIST (ID_WISH);

ALTER TABLE USUARIO ADD CONSTRAINTS FK_USU_CAR FOREIGN KEY (ID_CARRITO) REFERENCES CARRITO (ID_CARRITO);
ALTER TABLE CARRITO ADD CONSTRAINTS FK_CAR_TIC FOREIGN KEY (ID_TICKET) REFERENCES TICKET (ID_TICKET);

ALTER TABLE USUARIO ADD CONSTRAINTS FK_USU_VEN FOREIGN KEY (ID_VENDEDOR) REFERENCES USUARIO (ID_CLIENTE);
ALTER TABLE USUARIO ADD CONSTRAINTS FK_USU_SER FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIOS (ID_SERVICIO);

ALTER TABLE CARRITO ADD CONSTRAINTS FK_CAR_PRO FOREIGN KEY (ID_PRODUCTOS) REFERENCES PRODUCTOS (ID_PRODUCTOS);

ALTER TABLE TICKET ADD CONSTRAINTS FK_TIC_ENV FOREIGN KEY (ID_ENVIOS) REFERENCES ENVIOS (ID_ENVIOS);

